server:
  port: 8080

jwt:
  secret: "NosoyHugo-NosoyLeon-NosoyGonzalez-2026"
  expiration-minutes: 60

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: ms-api-gateway

  cloud:
    gateway:
      routes:
        # ms-catalogo
        - id: ms-catalogo
          uri: lb://ms-catalogo
          predicates:
            - Path=/api/v1/catalogo/**

        # ms-clientes
        - id: ms-clientes
          uri: lb://ms-clientes
          predicates:
            - Path=/api/v1/clientes/**

        # ms-pedidos
        - id: ms-pedidos
          uri: lb://ms-pedidos
          predicates:
            - Path=/api/v1/pedidos/**

        # ms-promociones
        - id: ms-promociones
          uri: lb://ms-promociones
          predicates:
            - Path=/api/v1/promociones/**

        # ms-reseñas
        - id: ms-resenas
          uri: lb://ms-resenas
          predicates:
            - Path=/api/v1/resenas/**

        # ms-notificaciones
        - id: ms-notificaciones
          uri: lb://ms-notificaciones
          predicates:
            - Path=/api/v1/notificaciones/**