server.port=8082
spring.application.name=ms-clientes

# Conexión a su propia base de datos independiente
springdoc.swagger-ui.operationSorter=method
spring.datasource.url=jdbc:mysql://localhost:3306/db_clientes?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Luciano1309@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect