# Puerto y nombre del microservicio
server.port=8085
spring.application.name=ms-resenas

# Configuración de Base de Datos MySQL (con creación automática de BD)
spring.datasource.url=jdbc:mysql://localhost:3306/db_resenas?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect